controllers:
    resource: '@KookaburraActivitiesBundle/Controller/'
    type: annotation
    schemes: [ 'https' ]
    # this is added to the beginning of all imported route URLs
    prefix: '/activities'
    # this is added to the beginning of all imported route names
    name_prefix: 'activities__'
